### PR TITLE
remove invalid concat string range check

### LINKED ISSUE #76: Investigate Concat
Concat feels somewhat off, especially the assertion about the source ranges. Needs investigation.

### LINKED ISSUE #108: Assertion failure on inline code within quote
Reproduction:

```
> Apparently, `1 +
> 1` equals crash.
```

> thread 'main' panicked at 'assertion failed: range.end == r.start || range.end + 1 == r.start', src/frontend/concat.rs:29:13

### PR DESCRIPTION
**Pull request by oberien**
Fix #108
Fix #76

### CODE REVIEW

File: src/frontend/concat.rs [hunk 1]
```diff
@@ -25,8 +25,13 @@ impl<'a> Iterator for Concat<'a> {
...
-            // TODO: why are both variants needed?
-            assert!(range.end == r.start || range.end + 1 == r.start);
+            // We can't assume that two text events follow each other directly here.
+            // For example a quote results in two text events following each other having different
+            // offsets in the original markdown content string:
+            // ```md
+            // > foo
+            // > bar
+            // ```
             range.end = r.end;
```
Comment (197g) [inline src/frontend/concat.rs:36]: Given this line, we should still at least assert `range.end <= r.start`, or modify the range to the `min, max` of the endpoints of both ranges.

Comment (oberien) [reply src/frontend/concat.rs:36]: There isn't a `min` or `max`, because in theory you could have a million nested quotes:

> > > > > > Nested Quote

Comment (oberien) [reply src/frontend/concat.rs:36]: I added the `end <= start` assertion.

**Review by 197g — APPROVED** [review]
